jwtToken=egov_secret_123
spring.application.name=sell-api
server.port=7000
spring.data.mongodb.uri=mongodb://103.75.182.242:30003/sell?retryWrites=true&w=majority&appName=Cluster0
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

chrome-driver=/usr/lib/chromium/chromedriver
#server.ssl.key-store=classpath:outbound-config/keystore.p12
#server.ssl.key- -password=1
#server.ssl.key-store-type=PKCS12
#server.ssl.enabled=true

server.tomcat.threads.max=400
server.tomcat.threads.min-spare=10
main-email=gavip13051995@gmail.com

#chrome-driver=D:/lib/chromedriver-win64/chromedriver.exe
#server.ssl.key-store=D:/Project/parttime/sell-api/jks.jks
#server.ssl.key-store-password=#*.winitech.com@
#server.ssl.key-store-type=JKS
#server.ssl.enabled=true
